//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub message_id: i32,
    pub sender_id: i32,
    pub chat_id: i32,
    pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(DeriveIntoActiveModel, Deserialize)]
pub struct CreateMessage {
    pub message_id: i32,
    pub sender_id: i32,
    pub chat_id: i32,
    pub text: String,
}

#[derive(DeriveIntoActiveModel, Deserialize)]
pub struct UpdateMessage {
    pub text: String,
}
